apiVersion: v1
kind: ServiceAccount
metadata:
  name: sfs-provisioner

---

kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: sfs-provisioner-runner
rules:
  - apiGroups: [""]
    resources: ["secrets"]
    verbs: ["create", "get", "delete"]
  - apiGroups: [""]
    resources: ["persistentvolumes"]
    verbs: ["get", "list", "watch", "create", "delete"]
  - apiGroups: [""]
    resources: ["persistentvolumeclaims"]
    verbs: ["get", "list", "watch", "update"]
  - apiGroups: ["storage.k8s.io"]
    resources: ["storageclasses"]
    verbs: ["get", "list", "watch"]
  - apiGroups: [""]
    resources: ["events"]
    verbs: ["list", "watch", "create", "update", "patch"]

---

kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: sfs-provisioner-role
subjects:
  - kind: ServiceAccount
    name: sfs-provisioner
    namespace: default
roleRef:
  kind: ClusterRole
  name: sfs-provisioner-runner
  apiGroup: rbac.authorization.k8s.io

---

kind: StatefulSet
apiVersion: apps/v1
metadata:
  name: sfs-provisioner
spec:
  podManagementPolicy: OrderedReady
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: sfs-provisioner
  serviceName: sfs-provisioner
  template:
    metadata:
      labels:
        app: sfs-provisioner
    spec:
      serviceAccount: sfs-provisioner
      containers:
        - name: sfs-provisioner
          securityContext:
            privileged: true
            capabilities:
              add: ["SYS_ADMIN"]
            allowPrivilegeEscalation: true
          image: quay.io/huaweicloud/sfs-provisioner:latest
          imagePullPolicy: Always
          args:
          # - "--vpcid=YOUR_VPCID mandatory for CFCR" 
            - "--v=5"
            - "--cloudconfig=$(CLOUD_CONFIG)"
          env:
            - name: CLOUD_CONFIG
              value: /etc/config/cloud-provider.ini #CFCR mod
          volumeMounts:
            - name: cloud-config-dir
              mountPath: /etc/config
        #    - name: cloud-data-dir                 #CFCR doesn't use cloud-init
        #     mountPath: /var/lib/cloud/data
      volumes:
        - name: cloud-config-dir
          hostPath:
            path: /var/vcap/jobs/kubelet/config   # CFCR mod
            type: Directory
       # - name: cloud-data-dir                   #CFCR doesn't use cloud-init
       #   hostPath:
       #     path: /var/lib/cloud/data
       #     type: DirectoryOrCreate
